name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.3"]
        ## service: [php-fpm, workspace, postgres, apache2, pgadmin, mailhog]
        service: [php-fpm, workspace]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        PHP_VERSION: ${{ matrix.php_version }}
      run: |
        cp .useEnv .env
        docker-compose build ${{ matrix.service }}


